---
kind: pipeline
type: kubernetes
name: compliance

steps:
  - name: golang:1.19
    image: golang:1.19
    commands:
      - go get
      - gofmt -d -s .
      - go test -cover -failfast -timeout 2s ./...

  - name: golang:1.20
    image: golang:1.20
    commands:
      - go get
      - gofmt -d -s .
      - go test -cover -failfast -timeout 2s ./...
